### PR TITLE
[pelican-bootstrap3] Update to bootstrap-3.4.1, bootswatch-3.4.1

### PR DESCRIPTION
**Pull request by jayaddison**
This cleans up [lighthouse](https://github.com/GoogleChrome/lighthouse) warnings about outstanding security vulnerabilities in `bootstrap-3.3.4`.

Thanks @StevenMaude for pointing out that it makes sense to update bootswatch at the same time as bootstrap.

This replaces a PR originally opened as #659 - I prematurely deleted the source repo, not realizing that I wouldn't be able to push further commits to that PR.

### CODE REVIEW

**Comment by jayaddison** [comment]
For future reference, the following `bash` script was useful to import the new `bootswatch` themes from the [bootswatch-3.4.1 tarball](https://github.com/thomaspark/bootswatch/archive/v3.4.1.tar.gz).

```
for i in bootswatch-3.4.1/*/*.min.css;
do
  cp $i bootstrap.`basename \`dirname $i\``.min.css;
done;
```

The `amelia` theme was [deprecated](https://github.com/thomaspark/bootswatch/commit/f88f3fb4acaf2d5f561370e00170ef358f1f1252) and [removed](https://github.com/thomaspark/bootswatch/commit/918b2a49ca6ac074bac47f6685cf3a687a4c6212) since `v3.2.0` and is removed here too.

**Comment by jayaddison** [comment]
cc @getpelican

**Comment by jayaddison** [comment]
cc @avaris @iKevinY (tagging you as recent committers/reviewers for Pelican, in case you can help for review; I'm not sure whether tagging @getpelican worked as a mention)

**Comment by jayaddison** [comment]
Thanks again @iKevinY!

**Comment by avaris** [comment]
I guess this is OK. I don't really know much about bootstrap :).

**Comment by jayaddison** [comment]
Thanks @avaris !  I've only used bootstrap (and bootswatch) as dependencies rather than being super familiar with them.

Hopefully the version bump is quite safe; I pulled in the upstream dist versions here, but it'd be nice if anyone could double-check / integrity-check them.

**Comment by jayaddison** [comment]
cc @justinmayer - just mentioning you on a couple of PRs which may be about ready for merge (glad to handle any additional feedback)

**Comment by jayaddison** [comment]
cc @Ninpo in case you might be able to provide a second opinion as a previous committer/library upgrader for this theme?

**Comment by Ninpo** [comment]
No objections to this update, runs OK with my test copy.

**Comment by jayaddison** [comment]
Great to hear, thanks again.

**Comment by justinmayer** [comment]
Many thanks to @jayaddison for the contribution and to @avaris, @iKevinY, and @Ninpo for reviewing. 🚀

**Pull request merged**
