### PR TITLE
Just Read: Extended metadata block for non-article pages

### PR DESCRIPTION
**Pull request by schtobia**
This is the second half of b062afff, so that the metadata block is now complete.

### CODE REVIEW

**Comment by justinmayer** [comment]
Thank you for the contribution, Tobias. The indenting style here seems a bit unorthodox. Is there a reason the conditional statements shouldn't be flush with the tags they affect?

**Comment by schtobia** [comment]
Not really. I thought the nested if's would be best recognizable by indenting them one further. But I'm not attached to this, just change it if you don't like it.

**Comment by schtobia** [comment]
Corrected the indenting.

**Comment by schtobia** [comment]
_push_

@justinmayer , are you still having concerns that I can help with?

**Comment by schtobia** [comment]
_ping_ Any chance of getting this into master?

**Comment by justinmayer** [comment]
Many thanks for your efforts, Tobias. Sincere apologies for the delay!

**Pull request merged**
