### PR TITLE
New theme

### PR DESCRIPTION
**Pull request by abr4xas**
New theme :)

### CODE REVIEW

**Comment by mischapeters** [comment]
:+1:

**Comment by justinmayer** [comment]
Thanks for the contribution, @abr4xas!

**Comment by justinmayer** [comment]
Added via 00c6ec8. Thanks for the contribution, @abr4xas!

**Comment by abr4xas** [comment]
You wellcome @justinmayer

**Comment by peco8** [comment]
Thank you so much @abr4xas , and I'm pretty excited :+1:

**Pull request closed without merging**
