### PR TITLE
Bricabrac: Replace outdated PAGES context with 'pages'

### PR DESCRIPTION
**Pull request by Bricabraque**
I hope I did it accordingly to your advice, let me know if it is not the case ;)

### CODE REVIEW

**Comment by adamatan** [comment]
Hi! 
FYI - I've made the `PAGES` ➔ `pages` substitution across all themes in PR https://github.com/getpelican/pelican-themes/pull/497, which also covers the HTML you've changed.

**Comment by Bricabraque** [comment]
Thanks !

**Comment by adamatan** [comment]
I think you also have a README change - are you re-opening this with the README change alone?

**Comment by Bricabraque** [comment]
That's right, it has been a certain time, I didn't check the commits.

**Comment by almet** [comment]
Great, thanks for taking the time to submit this (and sorry for the delay on accepting the changes :-))

**Pull request merged**
