### PR TITLE
Make pelican-bootstrap3 multilingual

### PR DESCRIPTION
**Pull request by jranke**

### CODE REVIEW

**Comment by justinmayer** [comment]
@jranke: Would you please resolve conflicts / rebase on current master?

**Comment by jranke** [comment]
OK, I'll have a go at it - would be cool to get this into the main development line!

**Comment by jranke** [comment]
@justinmayer OK, I think this is good to go.

**Comment by justinmayer** [comment]
Great! Would you please [squash your commits](https://github.com/getpelican/pelican/wiki/Git-Tips#squashing-commits)?

**Comment by jranke** [comment]
OK, done. It has been a long time since I prepared this pull request... I think users of the theme will have to add 

```
JINJA_EXTENSIONS = ['jinja2.ext.i18n']
````

to their config file as described in the updated README.md.

**Comment by gravyboat** [comment]
This PR has broken the bootstrap3 theme as noted here: https://github.com/getpelican/pelican-themes/issues/460#issuecomment-266931641

**Pull request merged**
