### PR TITLE
Bootstrap3: Skip '-square' part for vk.com social icon

### PR DESCRIPTION
**Pull request by agrrh**
Hello!

VK.com social network icon is broken.

`fa-vk-square` is absent in FontAwesome, so we should use just `fa-vk`.

This commit fixes the behavior.

### CODE REVIEW

**Comment by agrrh** [comment]
Hello again.

I assure you that it works correctly. Tested for months and ready-to-merge. :)

**Comment by agrrh** [comment]
@justinmayer I see you have right to merge in this repo. Could you please review this PR and probably approve it?

**Comment by justinmayer** [comment]
@agrrh: Would you please resolve conflicts / rebase on current master?

**Comment by agrrh** [comment]
@justinmayer 
Thank you for your time, but I will ask you to spare couple of minutes more.

Button "Resolve conflicts" leads to 404 error page.

And I'm afraid I don't know how to properly sync forked repo from original one to merge changes in. Could you please tell me how to do so?

**Comment by justinmayer** [comment]
Please review our [Git Tips](https://github.com/getpelican/pelican/wiki/Git-Tips) page.

**Comment by agrrh** [comment]
Resolved conflicts

**Comment by agrrh** [comment]
Nevermind, already done in #469

**Pull request closed without merging**
