### PR TITLE
GUM Theme: Only display "Tags" sidebar header if there are tags

### PR DESCRIPTION
**Pull request by stuaxo**

### CODE REVIEW

**Comment by jodumont** [comment]
in  **templates/sidebar.html**
just have to move 

`<h4>Tags</h4>`

after

`{% if tags and tags %}
`

and add `|length > 1`

to the if

the result should be something like this

```

{% if tags and tags|length > 1 %}
<h4>Tags</h4>

```

**Comment by stuaxo** [comment]
I think thats what the affect of my if tag_cloud in this patch should be ?

But I'm definitely happy to change it if needs be

**Comment by jodumont** [comment]
Hi stuaxo;

I'm sorry I did'nt realize your PR was already what I was proposing ;)

**Comment by stuaxo** [comment]
Cheers - was just sanity checking what I did by asking that, good we're on the same page - maybe the pull request can be accepted now :D

**Comment by justinmayer** [comment]
Thanks to @stuaxo for the fix and to @jodumont for reviewing.

**Pull request merged**
