### PR TITLE
uikit demo theme ported to pelican

### PR DESCRIPTION
**Pull request by inktrap**
I ported the theme from uikit's (http://getuikit.com) blog demo to pelican/jinja2. I am also eating my own dog food at https://blog.inktrap.org.

### CODE REVIEW

**Comment by justinmayer** [comment]
Thanks for the contribution, Valentin. Is there a reason for vendoring/bundling the entire UIkit framework?

**Comment by inktrap** [comment]
Personally I like to include and host the files myself, however I could
change it to use their CDN. Would that be better?

**Comment by inktrap** [comment]
@justinmayer

Personally I like to include and host the files myself, however I could
change it to use their CDN. Would that be better?

**Comment by almet** [comment]
Vendorizing seems to be an acceptable solution here from my perspective, let's merge this :)

**Comment by almet** [comment]
And thanks for the submission :)

**Pull request merged**
