### PR TITLE
[pelican-bootstrap3] Update to bootstrap-3.4.1

### PR DESCRIPTION
**Pull request by jayaddison**
This cleans up [lighthouse](https://github.com/GoogleChrome/lighthouse) warnings about outstanding security vulnerabilities in `bootstrap-3.3.4`.

### CODE REVIEW

**Comment by jayaddison** [comment]
(force-push to fix a misconfigured git `user.email`)

**Comment by jayaddison** [comment]
cc @justinmayer

**Comment by StevenMaude** [comment]
As a user of this theme, this proposed PR looks fine as a change but I have a couple of comments:

* The [Bootswatch themes](https://bootswatch.com/3/) should also be bumped to their v3.4.1 versions (`pelican-bootstrap3/static/css/bootstrap.*.min.css`) for consistency, and to avoid any possible bugs from having e.g. mismatched CSS and JS versions.
* Bootstrap v3.4.1 [was declared end-of-life earlier this year](https://blog.getbootstrap.com/2019/07/24/lts-plan/). Migrating this theme to a newer version of Bootstrap would be required to receive any further security fixes.

**Comment by jayaddison** [comment]
Thanks @StevenMaude .  Unfortunately because I deleted the source repository here, I've had to re-open this as https://github.com/getpelican/pelican-themes/pull/669 (thankfully at least github does store pull requests as refs, so I didn't lose the work so far).

As a minor user of `pelican` I'm not sure I can justify spending more time to upgrade beyond Bootstrap 3 even though it is EOL; hopefully this is still an improvement even if it's not cutting-edge.

**Pull request closed without merging**
