### PR TITLE
Add B-side theme

### PR DESCRIPTION
**Pull request by jhauh**
Adds a theme called B-side, which is a port of [Hugo B-side](https://hugo-b-side-demo.netlify.com/). 

Screenshots, documentation, and discussion can be found in the [README](https://github.com/fluffactually/pelican-b-side), and a demo site is available at https://fluffactually.github.io/pelican-b-side-demo/ 

I read a bunch of PRs before submitting this one and couldn't find any official checklist, but here are some things I found which seemed like a good idea and have been implemented:

- [x] Add theme as a submodule. I added this theme to follow the `pelican-themes` branch, which will be the stable release branch.
- [x] Include screenshots. Two included, and demo site.
- [x] Merge cleanly. This PR is ready to go right now, not sure what will happen if some of the other PRs are merged first (possible clash in `.gitmodules`).
- [x] Some Pelican theme best practices, e.g. strip tags from titles etc. 

Let me know if anything needs to be changed or if you have any feedback. Thanks!

### CODE REVIEW

**Comment by fluffactually** [comment]
cc @getpelican, @justinmayer, @iKevinY @avaris (tagging as recent reviewers on PRs)

Thanks for maintaining this repo it's a wonderful resource. Would any of you have a moment to check over this theme and let me know if any changes are needed?

**Comment by iKevinY** [comment]
@fluffactually Thanks for the ping; I don't normally get notifications on this repository! 😛

**Comment by fluffactually** [comment]
Hey @justinmayer would you mind merging this? Or let me know if changes are required.

**Comment by fluffactually** [comment]
Ping @justinmayer, apologies for the multiple pings but I'm not sure who else can merge PRs on this repo. Is there any chance you could merge this in if you're happy with it? Thanks!

**Comment by aleylara** [comment]
I can relate to your excitement. I made my first ever PR into this repo as eager as you are now. It was almost 2 years ago. It would be nice to get some feedback but themes understandably seem to have much lower priority in the workflow.

**Comment by justinmayer** [comment]
Apologies, @jhauh. What limited free time I've had recently I have tried to apply to preparing for the next Pelican release.

**Comment by justinmayer** [comment]
For the record, the upstream repository is located at: https://gitlab.com/jhauh/pelican_b_side

The demo is now located at: https://jhauh.gitlab.io/pelican_b_side_demo/

**Pull request merged**
