### PR TITLE
pelican-bootstrap3: Gtag support & reading time enhancements

### PR DESCRIPTION
**Pull request by srininara**

### CODE REVIEW

**Comment by srininara** [comment]
Is there any process to be followed to kick start the process of merging this PR? Please guide me to start it.

**Comment by srininara** [comment]
@justinmayer @almet ,
Please let me know if there is any process to be followed to kick start the process of sending and reviewing a PR. Please guide me to begin the process.

**Comment by srininara** [comment]
@tcarwash , @alexandrevicenzi ,
Since you are the developers who contributed the latest to this repo, I am asking you help to start the processing of getting this PR merged. Please help and guide me to begin the process.

**Comment by alexandrevicenzi** [comment]
There's nothing I can do here, I'm not a maintainer.

You just need to wait, but it seems that the last change in the project was in August.

**Review by justinmayer — APPROVED** [review]

**Pull request merged**
