### PR TITLE
fix some links in built-texts

### PR DESCRIPTION
**Pull request by octomike**

### CODE REVIEW

**Comment by justinmayer** [comment]
Thanks for the fixes, Michael. Regarding b808f60, the protocol-relative scheme is now [deemed an anti-pattern](http://www.paulirish.com/2010/the-protocol-relative-url/). Would you please amend that commit, changing those references to `https://`?

**Comment by octomike** [comment]
Okay, amended.

I thought there were issues when loading the disqus javascript via https:// when the base page is loaded with http:// , but I guess I was wrong.

**Comment by justinmayer** [comment]
My understanding is that the issue is when those two conditions are reversed.

**Comment by justinmayer** [comment]
Thanks for the fixes, Michael!

**Pull request merged**
