### PR TITLE
[pelican-bootstrap3] Upgrade to jquery-3.4.1

### PR DESCRIPTION
**Pull request by jayaddison**
This cleans up [lighthouse](https://github.com/GoogleChrome/lighthouse) warnings about outstanding security vulnerabilities in `jquery-3.3.1`.

### CODE REVIEW

**Comment by jayaddison** [comment]
(force-push to fix a misconfigured git `user.email`)

**Comment by jayaddison** [comment]
cc @justinmayer

**Comment by jayaddison** [comment]
cc @avaris @iKevinY (tagging you as recent committers/reviewers for Pelican, in case you can help for review; I'm not sure whether tagging @getpelican worked as a mention)

**Comment by jayaddison** [comment]
Thanks @iKevinY !

**Comment by jayaddison** [comment]
cc @justinmayer - just mentioning you on a couple of PRs which may be about ready for merge (glad to handle any additional feedback)

**Comment by jayaddison** [comment]
cc @Ninpo in case you might be able to provide a second opinion as a previous committer/library upgrader for this theme?

**Comment by Ninpo** [comment]
I appreciate the heads up. Works OK for me with the bootstrap/swatch update.

**Comment by jayaddison** [comment]
No problem - thanks for the check!

**Comment by justinmayer** [comment]
Many thanks to @jayaddison for the contribution and to @ivanhercaz, @iKevinY, and @Ninpo for reviewing. ✨ 

(@jayaddison: No need to cc: me, by the way, as I get notifications for all events in all Pelican repositories. I've had some personal things to address over the last couple of months, so there's a bit of a backlog at the moment that will slowly get cleared out.)

**Comment by jayaddison** [comment]
Thanks @justinmayer - and I'm sorry to hear that; all the best for working things out.

**Comment by ivanhercaz** [comment]
> I've had some personal things to address over the last couple of months, so there's a bit of a backlog at the moment that will slowly get cleared out.

Good luck! All my best wishes for you. Thank you very much for continue supporting and working on Pelican :heart:

**Pull request merged**
