### PR TITLE
Show source support added in pelican-bootstrap3

### PR DESCRIPTION
**Pull request by chrisramsay**
Update to pelican-boostrap3 to support the [Show Source](https://github.com/getpelican/pelican-plugins/tree/master/show_source) plugin.

### CODE REVIEW

**Comment by chrisramsay** [comment]
I made a mess of this one, left a file where I shouldn't. Closing this PR and will make another. Sorry.

**Comment by justinmayer** [comment]
There's no need to create a new PR. `git rebase` is your friend. See: https://github.com/getpelican/pelican/wiki/Git-Tips

**Comment by chrisramsay** [comment]
Apologies @justinmayer - I should have rebased indeed! Learned that for next time.

**Comment by justinmayer** [comment]
Fairly certain you could have still done it here.

**Pull request closed without merging**
