### PR TITLE
Added Pelican VSCode/Atom theme

### PR DESCRIPTION
**Pull request by frankcorneliusmartin**
VSCode + Atom colour scheme inspired theme: 
image

Ill be happy to make any necessary changes.

### CODE REVIEW

**Comment by justinmayer** [comment]
Hey Frank! Thank you for this submission. Your theme looks sharp and has nice attention to detail. Bravo! 👏 

Your PR is well-timed, as we have just begun the process of talking to theme developers about locating their theme repositories under the new [Pelican Themes](https://github.com/pelican-themes) organization, which we have set up to (1) improve discoverability, (2) enable easier collaboration with the Pelican dev team, and (3) encourage participation from the broader Pelican community.

What do you think? Will you join us in this quest? If so, we could make your theme one of the initial test cases as a Pip-installable package, one of the upcoming features planned for Pelican 5.0.

**Comment by frankcorneliusmartin** [comment]
Yes ill be happy to! Ill look at the other organization tomorrow.

**Comment by justinmayer** [comment]
That's great to hear, Frank. Once you have had a look, would you please [follow these transfer instructions](https://docs.github.com/en/repositories/creating-and-managing-repositories/transferring-a-repository#transferring-a-repository-owned-by-your-personal-account)? In step 4, select **Specify an organization or username** and then enter `pelican-themes` as the organization name. Then go on and complete steps 5 & 6.

Would you please let me know once that has been completed? Then I can take the next steps and ensure you have full permissions there. ✨ 

Also, if you are interested, we are doing a [Pelican sprint](https://github.com/getpelican/pelican/discussions/3212) this weekend. Feel free to join us in the chat today and help improve Pelican! https://web.libera.chat/?#pelican ✨

**Comment by justinmayer** [comment]
Awesome! The repository is now available at its new location under the Pelican Themes organization: https://github.com/pelican-themes/atom

Many thanks for the responsive action, Frank. Looking forward to collaborating with you! ✨

**Comment by frankcorneliusmartin** [comment]
Alright, the repo is now in the `pelican-themes` organization. I also seem to have write access 🎉. I'll reach out in the chat for further questions.

**Pull request closed without merging**
