### PR TITLE
Added tribaal-mnmlist as a submodule.

### PR DESCRIPTION
**Pull request by chrisglass**
Added my theme as a submodule. Thanks to the original mnmlist theme for the inspiration, it's awesome :)

### CODE REVIEW

**Comment by justinmayer** [comment]
Hey Chris. Thanks for the submission. When possible, we try to keep the number of theme variants to a minimum. I'm obviously not familiar with how your theme deviates from the mnmlist theme, but do you think it might be possible to submit your improvements, where appropriate, to the mnmlist theme itself?

**Comment by chrisglass** [comment]
Heya, it's not really possible to submit my changes upstream since it does change what the theme looks like (it changes the fonts on a fonts-only theme).

My theme is mostly there to scratch my own itch, I just thought others might be interested as well. but it's fine with me if it doesn't meet whatever guidelines there are. Feel free to close the PR if it doesn't meet your submission guidelines.

**Comment by almet** [comment]
Hey Chris ;)

Sorry for the delay on this, I'm doing some long overdue triaging work on this, so let's close this! Thanks for the idea to propose your changes here anyway ;)

**Comment by chrisglass** [comment]
Heya !

I should have closed this myself at the time, I thought I had. Sorry!

**Pull request closed without merging**
