### PR TITLE
Remove ops submodule

### LINKED ISSUE #463: No submodule mapping found in .gitmodules for path 'ops'
Attempting to do a recursive clone of this repository results in an error:

    $ git clone --recursive https://github.com/getpelican/pelican-themes
    Cloning into 'pelican-themes'...
    [...]
    No submodule mapping found in .gitmodules for path 'ops'

### PR DESCRIPTION
**Pull request by shouptech**
This would fix #463 though I'm not sure it's the right way to handle it. What happened to the ops submodule and why was it missing from .gitmodules?

### CODE REVIEW

**Comment by huiyiqun** [comment]
+1

**Comment by justinmayer** [comment]
@huiyiqun: Please don't add "+1" comments to any repo or project... ever. GitHub added reaction emoji for precisely this use case. Thanks! 😄

**Comment by huiyiqun** [comment]
I'm sorry.

The +1 is for that I could not ever clone the project with the `--recursive` argument.

**Comment by justinmayer** [comment]
@huiyiqun: No worries. Just trying to ensure the tools at our disposal are used as efficiently as possible, while minimizing unnecessary notifications to maintainers.

**Comment by justinmayer** [comment]
Thanks for reporting this, Mike. It's not clear why this seemingly spurious submodule was added in the first place.

Fixed via 879826b, which reverts commit 20ddb53d20c3e56dacc7fb488746156749391211.

**Pull request closed without merging**
